### ISSUE TITLE
Can't run DOT, how do I fix the following error: RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`

### ISSUE THREAD

**Issue by cts85** [sensity-ai/dot#106]
Hi friends,

I have a computer running Intel core i9 13980HX and RTX 4090. 
Recently I installed the Windows version of DOT, extracted everything from the ZIP file, but once I tried to run it I got the error below.
I tried everything to troubleshoot it but to no avail. Can someone please shed some light ? 
Thanks very much in advance.

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
torch\serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.parallel.data_parallel.DataParallel' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
torch\serialization.py:671: SourceChangeWarning: source code of class 'models.ArcMarginModel' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
torch\serialization.py:671: SourceChangeWarning: source code of class 'models.ResNet' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
torch\serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
torch\serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.batchnorm.BatchNorm2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
torch\serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.activation.PReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
torch\serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.pooling.MaxPool2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
torch\serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
torch\serialization.py:671: SourceChangeWarning: source code of class 'models.SEBlock' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
torch\serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.pooling.AdaptiveAvgPool2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
torch\serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
torch\serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.activation.Sigmoid' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
torch\serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.dropout.Dropout' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
torch\serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.batchnorm.BatchNorm1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
'strict' is an invalid keyword argument for load()
=== Control keys ===
1-9: Change avatar
1: C:/Users/gamin/Downloads/dot-001/dot/data/Brad Pitt.jpg
torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
torch\nn\functional.py:3609: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "ui.py", line 702, in start_button_event
  File "dot\__main__.py", line 67, in run
  File "dot\dot.py", line 131, in generate
  File "dot\commons\model_option.py", line 185, in generate_from_camera
  File "dot\commons\camera_utils.py", line 71, in camera_pipeline
  File "dot\simswap\option.py", line 180, in process_image
  File "dot\simswap\util\reverse2original.py", line 136, in reverse2wholeimage
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`

```

**Comment by Ghassen-Chaabouni** [comment]
We updated the executable for Windows to use the latest changes in dot.
This is the new version [link](https://drive.google.com/file/d/1HKj6kYXv8NczLcDI7xDXU7aWXpDGz6vg/view?usp=sharing).  You can try it and confirm if you are still getting the same error or not.

**Comment by hynxx** [comment]
> We updated the executable for Windows to use the latest changes in dot. This is the new version [link](https://drive.google.com/file/d/1HKj6kYXv8NczLcDI7xDXU7aWXpDGz6vg/view?usp=sharing). You can try it and confirm if you are still getting the same error or not.

I can confirm. The problem persisted on the new version with the exe file. Using a graphics card does not work with the SimSwap method, but does work with faceswap_cv2. Even if you transfer the missing files from github, which are described on the command line.

I have laptop with i5&RTX4060

**Comment by Ghassen-Chaabouni** [comment]
> > We updated the executable for Windows to use the latest changes in dot. This is the new version [link](https://drive.google.com/file/d/1HKj6kYXv8NczLcDI7xDXU7aWXpDGz6vg/view?usp=sharing). You can try it and confirm if you are still getting the same error or not.
> 
> I can confirm. The problem persisted on the new version with the exe file. Using a graphics card does not work with the SimSwap method, but does work with faceswap_cv2. Even if you transfer the missing files from github, which are described on the command line.
> 
> I have laptop with i5&RTX4060

My guess is that this issue is a lack of GPU memory. Maybe you can check the GPU memory consumption when running dot.

**Comment by hynxx** [comment]
> > > We updated the executable for Windows to use the latest changes in dot. This is the new version [link](https://drive.google.com/file/d/1HKj6kYXv8NczLcDI7xDXU7aWXpDGz6vg/view?usp=sharing). You can try it and confirm if you are still getting the same error or not.
> > 
> > 
> > I can confirm. The problem persisted on the new version with the exe file. Using a graphics card does not work with the SimSwap method, but does work with faceswap_cv2. Even if you transfer the missing files from github, which are described on the command line.
> > I have laptop with i5&RTX4060
> 
> My guess is that this issue is a lack of GPU memory. Maybe you can check the GPU memory consumption when running dot.

How can i fix it?

**Comment by Ghassen-Chaabouni** [comment]
> I have a GeForce RTX 4060 8GB and RAM 16GB. Isn't that enough for dot to work? Can you help me to fix it, please?

The memory should be enough. The minimum to run dot on gpu is 4GB of gpu memory.
Can you run SimSwap on CPU? You can do this by unchecking the option `use_gpu`.

**Comment by hynxx** [comment]
> > I have a GeForce RTX 4060 8GB and RAM 16GB. Isn't that enough for dot to work? Can you help me to fix it, please?
> 
> The memory should be enough. The minimum to run dot on gpu is 4GB of gpu memory. Can you run SimSwap on CPU? You can do this by unchecking the option `use_gpu`.

yes, but it will be very slow

**Comment by Ghassen-Chaabouni** [comment]
Can you run `nvidia-smi` in the command prompt and send me the output ?

**Comment by hynxx** [comment]
> Can you run `nvidia-smi` in the command prompt and send me the output ?

![2023-08-31_183258](https://github.com/sensity-ai/dot/assets/53821230/ee5ba009-e2c4-4f93-b178-8b13a13021b7)

**Comment by Ghassen-Chaabouni** [comment]
I found a similar issue here.
https://github.com/pytorch/pytorch/issues/70122

They said that:

> This seems to be an issue with older versions fo the NVIDIA drivers and CUDA. To whoever is facing this issue, the recommendation would be to update these to a newer version.

**Comment by Ghassen-Chaabouni** [comment]
@hynxx this error may be due to the `torch.linalg.inv` function. I replaced it with the same function from `cupy`.
I generated the executable. It's available [here](https://drive.google.com/file/d/10fdnSszaEbpGdCKxxeBFXQrkagxe3-RT/view?usp=sharing). Can you test it and confirm if it's working or not?
If it doesn't, I will move this operation to CPU because it seems to be working there.

**Comment by cts85** [comment]
> We updated the executable for Windows to use the latest changes in dot. This is the new version [link](https://drive.google.com/file/d/1HKj6kYXv8NczLcDI7xDXU7aWXpDGz6vg/view?usp=sharing). You can try it and confirm if you are still getting the same error or not.

Mate you're an absolute legend. Thanks very very much. 
It's working like a charm now, high resolution and all. 
Appreciate you taking the time to help with this issue.

**Comment by hynxx** [comment]
> > We updated the executable for Windows to use the latest changes in dot. This is the new version [link](https://drive.google.com/file/d/1HKj6kYXv8NczLcDI7xDXU7aWXpDGz6vg/view?usp=sharing). You can try it and confirm if you are still getting the same error or not.
> 
> Mate you're an absolute legend. Thanks very very much. It's working like a charm now, high resolution and all. Appreciate you taking the time to help with this issue.

Can you please describe what you did?

**Comment by hynxx** [comment]
> @hynxx this error may be due to the `torch.linalg.inv` function. I replaced it with the same function from `cupy`. I generated the executable. It's available [here](https://drive.google.com/file/d/10fdnSszaEbpGdCKxxeBFXQrkagxe3-RT/view?usp=sharing). Can you test it and confirm if it's working or not? If it doesn't, I will move this operation to CPU because it seems to be working there.

Thanks you. I'll test it later today.

**Comment by hynxx** [comment]
> @hynxx this error may be due to the `torch.linalg.inv` function. I replaced it with the same function from `cupy`. I generated the executable. It's available [here](https://drive.google.com/file/d/10fdnSszaEbpGdCKxxeBFXQrkagxe3-RT/view?usp=sharing). Can you test it and confirm if it's working or not? If it doesn't, I will move this operation to CPU because it seems to be working there.

Now everything works properly for me too and even faster than before. Appreciate you taking the time to help with this!
